let shopData = [

    //men
    {
        id: "item1",
        name: "Blue Sneakers",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/men/img1.jpg",
        price: 100,
        type: "Men",
    },
    {
        id: "item2",
        name: "Yellow Vans",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/men/img2.jpg",
        price: 150,
        type: "Men",
    },
    {
        id: "item3",
        name: "White Sport Shoes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/men/img3.jpg",
        price: 90,
        type: "Men",
    },
    {
        id: "item4",
        name: "Boots",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/men/img4.jpg",
        price: 200,
        type: "Men",
    },
    
    {
        id: "item5",
        name: "Zebra Flip FLop",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/men/img5.jpg",
        price: 50,
        type: "Men",
    },
    //women
    {
        id: "item6",
        name: "Colourful Shoes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/women/img1.jpg",
        price: 170,
        type: "Women",
    },
    {
        id: "item7",
        name: "Red Heels",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/women/img2.jpg",
        price: 199,
        type: "Women",
    },
    {
        id: "item8",
        name: "White Heels",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/women/img3.jpg",
        price: 199,
        type: "Women",
    },
    {
        id: "item9",
        name: "Sandal",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/women/img4.jpg",
        price: 89,
        type: "Women",
    },
    {
        id: "item10",
        name: "Beach Flip Flop",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/women/img5.jpg",
        price: 40,
        type: "Women",
    },
    //kids
    {
        id: "item11",
        name: "Red Boots",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/kids/img1.jpg",
        price: 100,
        type: "Kids",
    },
    {
        id: "item12",
        name: "Nike Sport",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/kids/img2.jpg",
        price: 199,
        type: "Kids",
    },
    {
        id: "item13",
        name: "Blue Air Jordan",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/kids/img3.jpg",
        price: 199,
        type: "Kids",
    },
    {
        id: "item14",
        name: "Blue Sneakers",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/kids/img4.jpg",
        price: 89,
        type: "Kids",
    },
    {
        id: "item15",
        name: "Pink shoes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repudiandae?",
        img: "images/kids/img5.jpg",
        price: 99,
        type: "Kids",
    },
];